### ISSUE TITLE
Drag'n Drop

### ISSUE THREAD

**Issue by SelinaWernike** [SelinaWernike/MMAudioUndVideo#2]
Bei einem Drop auf "Löschen" soll das Drag-Element gelöscht werden (mithilfe der ID). Allerdings wird im Moment nur der Link zum Placeholder-Bild geöffnet. Eventuell muss etwas mit prevent-Default genutzt werden

`deleteEdit.addEventListener("dragend", (ev) => {
    ev.preventDefault();
    let data = ev.dataTransfer.getData("id")
    console.log(data);
    let temp = document.querySelector("#" + data)
    temp.remove()
})`

Ist kein muss, aber vielleicht hat jemand ne Idee

**Comment by Tasemo** [comment]
Ist aller richtig so, das richtige Event ist allerdings "drop" an Stelle von "dragend". Dragend wird auf dem gedraggten Element aufgerufen, drop auf dem Zielelement. Und das preventDefault() verhindert genau das, was du beschrieben hast (Öffnen des Bildes).

**Comment by SelinaWernike** [comment]
Hab "dragend" durch "drop" ersetzt. Jetzt funktioniert es wie gewollt
